import { SearchItem } from './types';

export const STATIC_PAGES: SearchItem[] = [
  {
    id: 'page-home',
    type: 'page',
    title: 'Home',
    description: 'Explore, export and sync Apple Health to a database you run yourself. Open source, Apache-2.0',
    href: '/',
    icon: 'Home',
  },
  {
    id: 'page-app',
    type: 'page',
    title: 'App',
    description: 'The open-source iOS app that syncs Apple Health to your own database',
    href: '/app',
    icon: 'Smartphone',
  },
  {
    id: 'page-sync',
    type: 'page',
    title: 'Self-Hosted Database',
    description: 'The open-source example stack: PostgreSQL with TimescaleDB, Grafana, a web viewer, an API and an MCP server via Docker Compose',
    href: '/sync',
    icon: 'Database',
  },
  {
    id: 'page-consulting',
    type: 'page',
    title: 'Consulting',
    description: 'Help setting up, self-hosting, and building with PulsHealth, from the person who wrote it',
    href: '/consulting',
    icon: 'Users',
  },
  {
    id: 'page-support',
    type: 'page',
    title: 'Support',
    description: 'Documentation, issue tracker, and how to get help',
    href: '/support',
    icon: 'HelpCircle',
  },
  {
    id: 'page-about',
    type: 'page',
    title: 'About',
    description: 'Learn about PulsHealth and our mission',
    href: '/about',
    icon: 'Info',
  },
  {
    id: 'page-knowledge-base',
    type: 'page',
    title: 'Knowledge Base',
    description: 'Explore Apple HealthKit data types and documentation',
    href: '/knowledge-base',
    icon: 'BookOpen',
  },
  {
    id: 'page-knowledge-base-explore',
    type: 'page',
    title: 'Explore Health Data Types',
    description: 'Browse and search all HealthKit data types',
    href: '/knowledge-base/explore',
    icon: 'Search',
  },
  {
    id: 'page-docs',
    type: 'page',
    title: 'Documentation',
    description: 'The sync protocol spec, self-hosting, AI assistants, bulk export and the database guide',
    href: '/docs',
    icon: 'BookOpen',
  },
  {
    id: 'page-blog',
    type: 'page',
    title: 'Blog',
    description: 'Articles and insights about health data and technology',
    href: '/blog',
    icon: 'Newspaper',
  },
  {
    id: 'page-privacy',
    type: 'page',
    title: 'Privacy Policy',
    description: 'Where your health data goes, and where it does not',
    href: '/privacy',
    icon: 'Shield',
  },
];
