#!/usr/bin/env bash
# One-command self-host bootstrap for the PulsHealth reference stack.
#
#   scripts/bootstrap.sh [--time-zone <IANA zone>] [--lan] [--url <https URL>]
#                        [--build] [--no-qr]
#   scripts/bootstrap.sh --print-pairing
#   scripts/bootstrap.sh --issue-device <label> [--user <uuid>] [--url <URL>]
#
# From a fresh clone it:
#   1. creates server/.env from server/.env.example if there is none, with
#      every stack secret generated by `openssl rand -hex 32` (plus a shorter
#      WEB_AUTH_PASSWORD, the web viewer's login) and PULS_TIME_ZONE set
#      (from --time-zone, the PULS_TIME_ZONE environment variable, or the
#      host's zone; UTC as a last resort);
#   2. starts the stack — `docker compose up -d` in server/, pulling the
#      published ghcr.io/pulshealth images, or building them from this
#      checkout with --build (or PULS_BOOTSTRAP_BUILD=1);
#   3. waits until ingest answers GET /healthz and GET /v1/capabilities with
#      the token;
#   4. prints the pairing block for the app: the URL the phone should use,
#      the bearer token, the user ID, and a QR code of
#      puls://pair?url=<url-encoded>&token=<token>&user=<uuid>
#      (drawn by qrencode when it is installed, by the running ingest
#      container's own `ingest qr` otherwise, so no host package is needed);
#   5. prints the web viewer and Grafana URLs with their passwords.
#
# Re-running it is safe: an existing server/.env is never rewritten — the app
# holds PULS_TOKEN and the database volume holds POSTGRES_PASSWORD, so fresh
# secrets would strand both (rotate a single value instead: server/README.md,
# "Rotating secrets") — the stack is brought up if it is down, and the pairing
# block is printed again. --time-zone, --lan and --url update just their own
# key in an existing .env. --print-pairing prints the block from .env and
# touches nothing.
#
# --issue-device is the same block for a per-device token: it mints one in the
# running stack (`ingest devices issue`, what `make devices` wraps) and hands
# it the URL worked out here, so the command ends in a QR code that carries a
# token bound to one user instead of the shared PULS_TOKEN. The token exists
# in plaintext only in that output — nothing is written to server/.env.
#
# Ingest binds to 127.0.0.1 by default, which is right whenever a TLS proxy
# (reverse proxy, Tailscale Serve/Funnel) sits in front of port 8080: pass its
# HTTPS URL with --url and that is what the QR code carries. --lan sets
# INGEST_BIND_ADDR=0.0.0.0 so a phone on the same Wi-Fi can sync straight to
# http://<this host's LAN IP>:8080 — plaintext on your LAN, with the bearer
# token as the only protection. Fine on a network you control; nowhere else.
#
# Portable bash (3.2, macOS's default) for macOS and Linux; needs docker with
# the compose plugin, openssl and curl.

set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
root=$(cd "$script_dir/.." && pwd)
server_dir=$root/server
env_file=$server_dir/.env
env_example=$server_dir/.env.example

ingest_port=8080
default_user_id=5ea4d000-0000-4000-8000-000000000001
# Stack secrets bootstrap generates. GRAFANA_SMTP_PASSWORD is deliberately not
# among them: it is a Gmail app password you obtain yourself, and SMTP is off.
secrets='POSTGRES_PASSWORD PULS_TOKEN PULS_API_TOKEN PULS_MCP_TOKEN GRAFANA_PASSWORD GRAFANA_DB_PASSWORD API_DB_PASSWORD INGEST_DB_PASSWORD'
# Generated on a fresh .env too, but NOT required: an .env written before this
# key existed keeps working (the viewer is then open, as it always was), and
# emptying the value is the documented way to turn the login off again. Shorter
# than the 32-byte tokens because a person types this one into a browser.
optional_secrets='WEB_AUTH_PASSWORD'
# Same footing, at full length: the password of the web_app database role, which
# only the viewer's accounts mode (WEB_ACCOUNTS=true) connects as. An older
# .env without it simply has no web_app role (099_read_roles.sh skips it).
optional_db_secrets='WEB_DB_PASSWORD'

opt_time_zone=''
opt_lan=0
opt_url=''
# PULS_BOOTSTRAP_BUILD is the environment equivalent of --build; anything but
# empty/0/false/no turns it on, so `PULS_BOOTSTRAP_BUILD=true` works too.
case ${PULS_BOOTSTRAP_BUILD:-} in
  ''|0|false|FALSE|no|NO) opt_build=0 ;;
  *) opt_build=1 ;;
esac
opt_print_pairing=0
opt_print_url=0
opt_issue_device=''
opt_user=''
opt_qr=1

usage() {
  cat <<EOF
Usage: scripts/bootstrap.sh [options]

Creates server/.env (if absent) with generated secrets, starts the stack, and
prints the pairing block for the PulsHealth app. Safe to re-run.

Options:
  --time-zone <zone>  IANA zone the phone lives in (e.g. Europe/Berlin).
                      Default: \$PULS_TIME_ZONE, else this host's zone, else
                      UTC. Written to PULS_TIME_ZONE in server/.env.
  --lan               Bind ingest to 0.0.0.0 (INGEST_BIND_ADDR) so a phone on
                      the same Wi-Fi can use http://<LAN IP>:$ingest_port with
                      no TLS proxy. Plain HTTP on your LAN; the token is the
                      only protection. Default: 127.0.0.1 (proxy in front).
  --url <url>         The URL the phone should use instead of the LAN address,
                      e.g. the HTTPS URL of a TLS proxy or Tailscale Serve
                      listener. Stored as PULS_PUBLIC_URL in server/.env.
  --build             Build the four app images from this checkout
                      (server/compose.build.yml) instead of pulling
                      ghcr.io/pulshealth/*. Also: PULS_BOOTSTRAP_BUILD=1.
  --print-pairing     Print the pairing block from server/.env and exit;
                      starts and changes nothing.
  --issue-device <label>
                      Issue a per-device token in the running stack and print
                      its pairing block and QR code, then exit. The label is
                      what \`make devices ARGS=list\` shows ("My iPhone"). With
                      --url, that URL goes into this code only; server/.env is
                      not changed. The token is shown this once.
  --user <uuid>       With --issue-device: the user the token is bound to.
                      Default: PULS_USER_ID from server/.env, else the seeded
                      default user. A new UUID creates that user.
  --print-url         Print only the URL the pairing block would carry (empty
                      when there is none yet) and exit. \`make devices\` uses it.
  --no-qr             Skip the QR code (print the payload as text only).
  -h, --help          This help.
EOF
}

die() {
  printf 'bootstrap: %s\n' "$*" >&2
  exit 1
}

note() {
  printf '%s\n' "$*"
}

step() {
  printf '\n==> %s\n' "$*"
}

need() {
  local cmd
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || die "$cmd is required but not installed"
  done
}

# ---------------------------------------------------------------------------
# .env handling. Values are read and written as plain KEY=value lines; a
# commented-out placeholder (# KEY=...) from .env.example is turned into the
# live line when a key is first set.

env_get() {
  local key=$1 line
  line=$( { grep -E "^${key}=" "$env_file" || true; } | tail -n 1)
  line=${line#*=}
  case $line in
    \"*\") line=${line#\"}; line=${line%\"} ;;
    \'*\') line=${line#\'}; line=${line%\'} ;;
  esac
  printf '%s' "$line"
}

env_set() {
  local key=$1 value=$2 pattern tmp
  if grep -qE "^${key}=" "$env_file"; then
    pattern="^${key}="
  elif grep -qE "^#[[:space:]]*${key}=" "$env_file"; then
    pattern="^#[[:space:]]*${key}="
  else
    printf '%s=%s\n' "$key" "$value" >>"$env_file"
    return
  fi
  tmp=$(mktemp "${env_file}.XXXXXX")
  # The replacement line travels through the environment, not `awk -v`, which
  # would expand backslash escapes inside the value.
  PULS_ENV_LINE="${key}=${value}" awk -v pattern="$pattern" '
    BEGIN { line = ENVIRON["PULS_ENV_LINE"] }
    !replaced && $0 ~ pattern { print line; replaced = 1; next }
    { print }
  ' "$env_file" >"$tmp"
  mv "$tmp" "$env_file"
}

# Whether the server accepts PULS_TOKEN at all: it does not when
# PULS_ALLOW_SHARED_TOKEN is false or the value is empty, in which case only
# per-device tokens (`make devices ARGS='issue …'`) authenticate.
shared_token_enabled() {
  local token allow
  token=$(env_get PULS_TOKEN)
  allow=$(env_get PULS_ALLOW_SHARED_TOKEN)
  [[ -n $token ]] || return 1
  case $allow in
    0|false|FALSE|False|f|F|no|NO|No|n|N) return 1 ;;
  esac
  return 0
}

# ---------------------------------------------------------------------------
# Time zone.

valid_zone() {
  local zone=$1
  [[ $zone =~ ^[A-Za-z0-9_+-]+(/[A-Za-z0-9_+-]+)*$ ]] || return 1
  # Every host with a zoneinfo database can check the name properly; the
  # migrate service checks it again against pg_timezone_names.
  if [[ -d /usr/share/zoneinfo ]]; then
    [[ -f /usr/share/zoneinfo/$zone ]] || return 1
  fi
  return 0
}

# Best-effort host zone: the IANA name /etc/localtime points at on macOS,
# timedatectl or /etc/timezone or the /etc/localtime target on Linux.
detect_time_zone() {
  local zone='' target=''
  case $(uname -s) in
    Darwin)
      target=$(readlink /etc/localtime 2>/dev/null || true)
      ;;
    Linux)
      if command -v timedatectl >/dev/null 2>&1; then
        zone=$(timedatectl show -p Timezone --value 2>/dev/null || true)
      fi
      if [[ -z $zone && -r /etc/timezone ]]; then
        zone=$(head -n 1 /etc/timezone 2>/dev/null || true)
      fi
      if [[ -z $zone ]]; then
        target=$(readlink -f /etc/localtime 2>/dev/null || true)
      fi
      ;;
  esac
  if [[ -z $zone && -n $target && $target == *zoneinfo/* ]]; then
    zone=${target#*zoneinfo/}
  fi
  if [[ -n $zone ]] && valid_zone "$zone"; then
    printf '%s' "$zone"
  fi
}

# ---------------------------------------------------------------------------
# Network helpers.

# The host's IPv4 on the interface that carries the default route.
detect_lan_ip() {
  local ip='' iface=''
  case $(uname -s) in
    Darwin)
      iface=$(route -n get default 2>/dev/null | awk '/interface:/ { print $2; exit }' || true)
      if [[ -n $iface ]]; then
        ip=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
      fi
      ;;
    Linux)
      if command -v ip >/dev/null 2>&1; then
        ip=$(ip -4 route get 1.1.1.1 2>/dev/null \
          | awk '{ for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit } }' || true)
      fi
      if [[ -z $ip ]]; then
        ip=$(hostname -I 2>/dev/null | awk '{ print $1 }' || true)
      fi
      ;;
  esac
  printf '%s' "$ip"
}

# Mirrors the app's rule for plain http (ServerURLValidation.swift):
# localhost, *.local, loopback, RFC 1918 and link-local hosts only.
is_local_network_host() {
  local host=$1
  case $host in
    localhost|*.localhost|*.local) return 0 ;;
    127.*|10.*|192.168.*|169.254.*) return 0 ;;
    172.1[6-9].*|172.2[0-9].*|172.3[01].*) return 0 ;;
  esac
  return 1
}

url_host() {
  local rest=${1#*://}
  rest=${rest%%/*}
  rest=${rest%%:*}
  printf '%s' "$rest"
}

# Percent-encodes everything but the unreserved characters, byte by byte.
urlencode() {
  local LC_ALL=C s=$1 out='' c i
  for ((i = 0; i < ${#s}; i++)); do
    c=${s:i:1}
    case $c in
      [A-Za-z0-9.~_-]) out+=$c ;;
      *) out+=$(printf '%%%02X' "'$c") ;;
    esac
  done
  printf '%s' "$out"
}

# ---------------------------------------------------------------------------
# Compose.

compose() {
  if [[ $opt_build == 1 ]]; then
    docker compose --project-directory "$server_dir" \
      -f "$server_dir/docker-compose.yml" -f "$server_dir/compose.build.yml" "$@"
  else
    docker compose --project-directory "$server_dir" \
      -f "$server_dir/docker-compose.yml" "$@"
  fi
}

# Where this host can reach ingest itself. INGEST_BIND_ADDR is the interface
# Compose publishes port 8080 on: loopback by default, 0.0.0.0 with --lan
# (still reachable at 127.0.0.1), or one specific address a user pinned by
# hand — in which case that is the only address that answers.
probe_base() {
  local bind=$1
  case $bind in
    ''|0.0.0.0|'::'|'[::]'|'*') bind=127.0.0.1 ;;
  esac
  printf 'http://%s:%s' "$bind" "$ingest_port"
}

wait_for_ingest() {
  local base=$1 token=$2 deadline=$((SECONDS + 300)) body status version
  printf 'Waiting for ingest at %s ' "$base"
  while :; do
    body=$(curl -fsS -m 3 "$base/healthz" 2>/dev/null || true)
    [[ $body == *'"ok":true'* ]] && break
    if ((SECONDS >= deadline)); then
      echo
      compose ps >&2 || true
      die "ingest did not answer $base/healthz within 5 minutes. Look at: docker compose -f server/docker-compose.yml logs migrate ingest"
    fi
    printf '.'
    sleep 3
  done
  echo " ok"
  status=$(curl -s -o /dev/null -m 5 -w '%{http_code}' \
    -H "Authorization: Bearer $token" -H 'X-Puls-Protocol: 1' \
    "$base/v1/capabilities" || true)
  if ! shared_token_enabled; then
    # Nothing to present: a 401 here is the server refusing the shared
    # token as configured, which is the healthy answer.
    [[ $status == 401 || $status == 200 ]] || die "GET $base/v1/capabilities answered HTTP $status (expected 401 with the shared token disabled). Look at: docker compose -f server/docker-compose.yml logs ingest"
    note "Ingest is up. The shared token is disabled, so the phone pairs with a device token (below)."
    return 0
  fi
  [[ $status == 200 ]] || die "GET $base/v1/capabilities answered HTTP $status with PULS_TOKEN from server/.env (expected 200). Is the running stack using this .env? Try: docker compose -f server/docker-compose.yml up -d ingest"
  version=$(curl -fsS -m 5 -H "Authorization: Bearer $token" -H 'X-Puls-Protocol: 1' \
    "$base/v1/capabilities" 2>/dev/null | sed -n 's/.*"version":"\([^"]*\)".*/\1/p' || true)
  note "Ingest is up${version:+ (version $version)} and accepts the token."
}

# ---------------------------------------------------------------------------
# Pairing block.

# Works out the URL the phone should use, from server/.env and this host, into
# two globals (bash 3.2 has no namerefs): pair_url — empty when there is
# nothing the phone could reach yet — and reachable_note, the sentence that
# says where it came from or what to do about it. A container cannot do this
# for itself (it sees neither the proxy in front of it nor the host's LAN
# address), which is why --issue-device and `make devices` pass the result in.
pair_url=''
reachable_note=''
resolve_pairing_url() {
  local bind public_url lan_ip
  bind=$(env_get INGEST_BIND_ADDR)
  public_url=$(env_get PULS_PUBLIC_URL)
  [[ -n $bind ]] || bind=127.0.0.1
  public_url=${public_url%/}
  lan_ip=$(detect_lan_ip)

  pair_url=''
  reachable_note=''
  if [[ -n $public_url ]]; then
    pair_url=$public_url
    reachable_note="PULS_PUBLIC_URL from server/.env — the TLS proxy in front of port $ingest_port."
  elif [[ $bind != 127.0.0.1 && $bind != localhost ]]; then
    if [[ $bind == 0.0.0.0 ]]; then
      if [[ -n $lan_ip ]]; then
        pair_url="http://$lan_ip:$ingest_port"
        reachable_note="This host's LAN address (ingest is bound to every interface). Works for a phone on the same Wi-Fi: plain HTTP, the token is the only protection. Anywhere else needs a TLS proxy or Tailscale Serve/Funnel URL — pass it with --url."
      else
        reachable_note="Ingest is bound to every interface, but this host's LAN IPv4 could not be detected: use http://<this host's LAN IP>:$ingest_port on a phone on the same Wi-Fi, or --url for a TLS proxy."
      fi
    else
      pair_url="http://$bind:$ingest_port"
      reachable_note="INGEST_BIND_ADDR from server/.env."
      if ! is_local_network_host "$bind"; then
        reachable_note="$reachable_note The app refuses plain http:// outside the local network (10.x, 172.16-31.x, 192.168.x, *.local); put a TLS proxy in front and pass its URL with --url."
      fi
    fi
  else
    reachable_note="Ingest listens on 127.0.0.1:$ingest_port only (the default), so the phone cannot reach it yet. Either
              - put a TLS proxy or Tailscale Serve/Funnel in front of it (server/README.md, \"Exposing the server\")
                and re-run with --url https://<its host>, or
              - re-run with --lan for plain HTTP to http://${lan_ip:-<LAN IP of this host>}:$ingest_port on your own Wi-Fi."
  fi
}

# The one command that ends in a QR code for a per-device token, with the
# user filled in when it is not the default one.
issue_device_hint() {
  local user_id=$1
  if [[ $user_id == "$default_user_id" ]]; then
    printf 'scripts/bootstrap.sh --issue-device "<label, e.g. My iPhone>"'
  else
    printf 'scripts/bootstrap.sh --issue-device "<label, e.g. My iPhone>" --user %s' "$user_id"
  fi
}

# Draws the payload as a terminal QR code: qrencode when the host has it, else
# the running ingest container's own renderer (`ingest qr`, server/ingest/qr.go)
# — exec rather than `run`, so it is whatever image the stack is actually on
# (published or built from this checkout) and nothing is pulled, built or
# started for the sake of a picture. The payload goes in on stdin both times:
# it holds the token, and arguments are readable in `ps`. A stack that is down,
# or an older image pinned by PULS_VERSION that has no `qr` subcommand, ends in
# the hint — a missing QR code never fails the bootstrap.
render_qr() {
  local payload=$1 drawn=''
  [[ $opt_qr == 1 ]] || return 0
  echo
  if command -v qrencode >/dev/null 2>&1; then
    printf '%s' "$payload" | qrencode -t ANSIUTF8 -m 2
    return 0
  fi
  drawn=$(printf '%s' "$payload" | compose exec -T ingest /ingest qr 2>/dev/null) || drawn=''
  # An image without the subcommand ignores the argument and tries to start a
  # second server, which dies on the taken port — but only print what is
  # recognisably a drawing, never that server's log lines.
  if [[ $drawn == *'█'* ]]; then
    printf '%s\n' "$drawn"
  else
    echo " (No QR code: the ingest container could not draw one — it is not running, or its image predates"
    echo "  \`ingest qr\` — and qrencode is not installed. Start or upgrade the stack, or brew install qrencode /"
    echo "  apt install qrencode; then scripts/bootstrap.sh --print-pairing.)"
  fi
}

print_pairing() {
  local token user_id payload hr
  token=$(env_get PULS_TOKEN)
  user_id=$(env_get PULS_USER_ID)
  [[ -n $user_id ]] || user_id=$default_user_id
  resolve_pairing_url

  hr='------------------------------------------------------------------------'
  echo
  echo "$hr"
  echo " PulsHealth pairing"
  echo "$hr"
  printf ' %-12s %s\n' "Server URL" "${pair_url:-(none yet)}"
  printf ' %-12s %s\n' '' "$reachable_note"
  if shared_token_enabled; then
    printf ' %-12s %s\n' "Token" "$token"
  else
    printf ' %-12s %s\n' "Token" "(shared token disabled — a device token is shown only when it is issued; see below)"
  fi
  printf ' %-12s %s\n' "User ID" "$user_id"
  echo
  echo " In the app: Settings > Server, scan the QR code or enter the three values, then Test Connection."
  echo " Keep the token private: with it, anyone who can reach the URL can upload and delete your data."
  echo "$hr"

  if ! shared_token_enabled; then
    # There is no token here to put in a code: only hashes of device tokens
    # are stored. Say how to get one rather than ending without a word.
    echo
    echo " No QR code: the shared token is disabled, and a device token can only be shown when it is issued."
    echo " This issues one and prints its QR code:"
    echo "   $(issue_device_hint "$user_id")"
    echo
    return 0
  fi
  [[ -n $pair_url ]] || return 0
  payload="puls://pair?url=$(urlencode "$pair_url")&token=$(urlencode "$token")&user=$(urlencode "$user_id")"
  render_qr "$payload"
  echo
  echo " Pairing payload (what the QR code encodes):"
  echo " $payload"
  echo
}

# --issue-device: mint a per-device token and print its pairing block. The
# work is `ingest devices issue` inside the running container — exec, like
# render_qr, so it is the image the stack is on and the DATABASE_URL it already
# holds; this script only supplies the URL. Everything is checked before the
# call, because a token minted for a code nobody can scan is a row to revoke.
issue_device() {
  local label=$1 user_id=$2 status=0
  local -a extra=()
  [[ -n $user_id ]] || user_id=$(env_get PULS_USER_ID)
  [[ -n $user_id ]] || user_id=$default_user_id
  [[ $user_id =~ ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ ]] \
    || die "--user '$user_id' is not a UUID"

  resolve_pairing_url
  if [[ -n $opt_url ]]; then
    pair_url=${opt_url%/}
  fi
  [[ -n $pair_url ]] || die "there is no URL the phone could use yet, so no token was issued.
           $reachable_note
           Or name the URL for this one code: --issue-device \"$label\" --url https://<host>"

  [[ -n $(compose ps -q --status running ingest 2>/dev/null) ]] \
    || die "the ingest container is not running, so no token was issued. Start the stack (scripts/bootstrap.sh, or make up) and re-run."

  [[ $opt_qr == 1 ]] || extra+=(--no-qr)
  echo
  # -T and no stdin: nothing here is interactive, and a pseudo-terminal would
  # only add carriage returns to output someone may be capturing.
  compose exec -T ingest /ingest devices issue \
    --user "$user_id" --name "$label" --url "$pair_url" ${extra[@]+"${extra[@]}"} </dev/null || status=$?
  if [[ $status == 2 ]]; then
    die "the running ingest image refused the command (above). If it is complaining about --url, the image predates
           pairing codes for device tokens: upgrade it (PULS_VERSION in server/.env, then make pull up), or issue the token
           the old way — make devices ARGS='issue --user $user_id --name \"$label\"' — and type the values into the app."
  fi
  [[ $status == 0 ]] || die "issuing the device token failed (output above)."
}

# The two browser surfaces, printed after the pairing block and by
# --print-pairing, so the viewer password is never something you have to go
# looking for in .env.
print_services() {
  local web_bind web_password
  web_bind=$(env_get WEB_BIND_ADDR)
  case $web_bind in ''|0.0.0.0|'::'|'[::]') web_bind=127.0.0.1 ;; esac
  web_password=$(env_get WEB_AUTH_PASSWORD)
  if [[ -n $web_password ]]; then
    note "Web viewer: http://$web_bind:3001   (any username, password $web_password — WEB_AUTH_PASSWORD in server/.env)"
  else
    note "Web viewer: http://$web_bind:3001   !! no login: WEB_AUTH_PASSWORD is empty in server/.env, so anything that"
    note "            can reach that port reads your health data. Set it and \`docker compose up -d web\` to add one."
  fi
  note "Grafana:    http://127.0.0.1:3000   (user $(env_get GRAFANA_USER), password GRAFANA_PASSWORD in server/.env)"
}

# ---------------------------------------------------------------------------
# Main.

while (($# > 0)); do
  case $1 in
    --time-zone) [[ $# -ge 2 ]] || die "--time-zone needs a value"; opt_time_zone=$2; shift 2 ;;
    --time-zone=*) opt_time_zone=${1#*=}; shift ;;
    --lan) opt_lan=1; shift ;;
    --url) [[ $# -ge 2 ]] || die "--url needs a value"; opt_url=$2; shift 2 ;;
    --url=*) opt_url=${1#*=}; shift ;;
    --build) opt_build=1; shift ;;
    --print-pairing) opt_print_pairing=1; shift ;;
    --print-url) opt_print_url=1; shift ;;
    --issue-device) [[ $# -ge 2 ]] || die "--issue-device needs a label, e.g. --issue-device \"My iPhone\""; opt_issue_device=$2; shift 2 ;;
    --issue-device=*) opt_issue_device=${1#*=}; shift ;;
    --user) [[ $# -ge 2 ]] || die "--user needs a value"; opt_user=$2; shift 2 ;;
    --user=*) opt_user=${1#*=}; shift ;;
    --no-qr) opt_qr=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; die "unknown option: $1" ;;
  esac
done

[[ -f $env_example ]] || die "cannot find $env_example — run from a PulsHealth checkout"

if [[ -n $opt_url ]]; then
  [[ $opt_url == http://* || $opt_url == https://* ]] || die "--url must start with http:// or https://"
  if [[ $opt_url == http://* ]] && ! is_local_network_host "$(url_host "$opt_url")"; then
    die "the app refuses plain http:// outside the local network; --url must be https:// for $(url_host "$opt_url")"
  fi
fi
[[ -z $opt_user || -n $opt_issue_device ]] || die "--user only applies to --issue-device"

if [[ $opt_print_url == 1 ]]; then
  [[ -f $env_file ]] || die "server/.env does not exist yet; run scripts/bootstrap.sh first"
  resolve_pairing_url
  printf '%s\n' "$pair_url"
  exit 0
fi

if [[ -n $opt_issue_device ]]; then
  [[ -f $env_file ]] || die "server/.env does not exist yet; run scripts/bootstrap.sh first"
  need docker
  issue_device "$opt_issue_device" "$opt_user"
  exit 0
fi

if [[ $opt_print_pairing == 1 ]]; then
  [[ -f $env_file ]] || die "server/.env does not exist yet; run scripts/bootstrap.sh first"
  token=$(env_get PULS_TOKEN)
  if shared_token_enabled; then
    [[ $token != change-me ]] \
      || die "PULS_TOKEN is still 'change-me' in server/.env; set it (openssl rand -hex 32), empty it to use device tokens only, or delete .env and re-run scripts/bootstrap.sh"
  fi
  print_pairing
  print_services
  exit 0
fi

need docker openssl curl
docker compose version >/dev/null 2>&1 || die "docker compose (the Compose v2 plugin) is required"
docker info >/dev/null 2>&1 || die "the Docker daemon is not running or not reachable"

# --- server/.env --------------------------------------------------------------

umask 077
if [[ -f $env_file ]]; then
  step "Using the existing server/.env"
  note "Secrets are never regenerated by this script (the app holds PULS_TOKEN and the database volume holds"
  note "POSTGRES_PASSWORD; new values would strand both). To rotate one, see server/README.md, \"Rotating secrets\"."
  missing=''
  for key in $secrets; do
    # An empty or disabled PULS_TOKEN is a choice (device tokens only),
    # not a placeholder.
    if [[ $key == PULS_TOKEN ]] && ! shared_token_enabled; then
      continue
    fi
    value=$(env_get "$key")
    if [[ -z $value || $value == change-me ]]; then
      missing="$missing $key"
    fi
  done
  if [[ -n $missing ]]; then
    die "server/.env still has placeholder values for:$missing — set each one (openssl rand -hex 32) and re-run"
  fi
else
  step "Creating server/.env from .env.example"
  cp "$env_example" "$env_file"
  chmod 600 "$env_file"
  for key in $secrets; do
    env_set "$key" "$(openssl rand -hex 32)"
  done
  for key in $optional_secrets; do
    env_set "$key" "$(openssl rand -hex 12)"
  done
  for key in $optional_db_secrets; do
    env_set "$key" "$(openssl rand -hex 32)"
  done
  note "Generated: $secrets $optional_secrets $optional_db_secrets"

  zone=''
  zone_source=''
  if [[ -n $opt_time_zone ]]; then
    zone=$opt_time_zone; zone_source='--time-zone'
  elif [[ -n ${PULS_TIME_ZONE:-} ]]; then
    zone=$PULS_TIME_ZONE; zone_source='the PULS_TIME_ZONE environment variable'
  else
    zone=$(detect_time_zone); zone_source="this host's clock"
  fi
  if [[ -n $zone ]] && ! valid_zone "$zone"; then
    rm -f "$env_file"
    die "'$zone' (from $zone_source) is not an IANA time zone name such as Europe/Berlin; pass --time-zone"
  fi
  if [[ -n $zone ]]; then
    env_set PULS_TIME_ZONE "$zone"
    note "PULS_TIME_ZONE=$zone (from $zone_source). It must be the zone your phone lives in — every daily"
    note "view buckets by this calendar. Wrong? Edit server/.env and \`docker compose up -d\` (or --time-zone)."
  else
    env_set PULS_TIME_ZONE UTC
    echo
    note "!!  PULS_TIME_ZONE=UTC: this host's time zone could not be detected. Every daily view buckets by"
    note "!!  this calendar and it MUST match the phone's zone, or days split in two. Set it before the"
    note "!!  first sync: scripts/bootstrap.sh --time-zone Europe/Berlin (or edit server/.env)."
    echo
  fi
fi

if [[ -n $opt_time_zone ]]; then
  valid_zone "$opt_time_zone" || die "'$opt_time_zone' is not an IANA time zone name such as Europe/Berlin"
  if [[ $(env_get PULS_TIME_ZONE) != "$opt_time_zone" ]]; then
    env_set PULS_TIME_ZONE "$opt_time_zone"
    note "PULS_TIME_ZONE=$opt_time_zone written to server/.env."
  fi
fi
if [[ $opt_lan == 1 && $(env_get INGEST_BIND_ADDR) != 0.0.0.0 ]]; then
  env_set INGEST_BIND_ADDR 0.0.0.0
  note "INGEST_BIND_ADDR=0.0.0.0 written to server/.env: ingest is published on every interface of this host,"
  note "plain HTTP, with the bearer token as the only protection. Meant for a phone on the same Wi-Fi on a"
  note "network you control; to go back, set it to 127.0.0.1 and \`docker compose up -d\`."
fi
if [[ -n $opt_url && $(env_get PULS_PUBLIC_URL) != "${opt_url%/}" ]]; then
  env_set PULS_PUBLIC_URL "${opt_url%/}"
  note "PULS_PUBLIC_URL=${opt_url%/} written to server/.env (used for the pairing block only)."
fi

# --- the stack ----------------------------------------------------------------

if [[ $opt_build == 1 ]]; then
  step "Building the app images from this checkout and starting the stack"
  if command -v git >/dev/null 2>&1; then
    DEPLOY_COMMIT=$(git -C "$root" rev-parse HEAD 2>/dev/null || echo unknown)
    export DEPLOY_COMMIT
  fi
  compose up -d --build \
    || die "the build failed. The output above says which image; re-run after fixing it."
else
  step "Starting the stack (pulling ghcr.io/pulshealth images as needed)"
  compose up -d || die "\`docker compose up -d\` failed (output above). If it could not pull
       ghcr.io/pulshealth/{ingest,api,mcp,web} — no release has been published yet, the
       packages are still private, or PULS_VERSION names a tag that does not exist — build
       the images from this checkout instead: scripts/bootstrap.sh --build"
fi

step "Checking ingest"
wait_for_ingest "$(probe_base "$(env_get INGEST_BIND_ADDR)")" "$(env_get PULS_TOKEN)"

print_pairing
print_services
note "Later: \`make pairing\` re-prints this block; \`make logs\`, \`make ps\`, \`make down\`; server/README.md has the rest."
note "Backups are opt-in and off: \`make backup\` takes one now, \`docker compose --profile backup up -d backup\` runs"
note "on a schedule (server/README.md, \"Backup & restore\"). Nothing else copies your data anywhere."
